title: "Aporia Ananta"
description: "Tafakur dan lain sebagainya"
baseurl: ""
url: "https://kothar.me"

markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      lang: id

plugins:
  - jekyll-redirect-from

exclude:
  - README.md
  - docs/
  - Gemfile
  - Gemfile.lock
